project_id              = "cogent-wall-467021-d4"
region                  = "us-central1"
zone                    = "us-central1-a"
domain                  = "n8n.moraran.com"
n8n_basic_auth_password = "changeme"
gcs_backup_bucket       = "n8n-backups"
scripts_repo_url        = "https://raw.githubusercontent.com/moraran/terraform-gcp-n8n/main"
